### ISSUE TITLE
`operator*=` broken?

### ISSUE THREAD

**Issue by DavidToneian** [uekstrom/libtaylor#1]
I hope I understood the way `libtaylor` should work from the example and the quick glances I took at the code. If what I'm reporting is merely wrong use and not a bug, please let me know.

When I have a computation that uses `operator*=`, as in `f` in the following,
```C++
#include <iostream>
#include "taylor.hpp"

template<typename T>
T f(const T& x)
{
  T tmp = x;
  tmp *= tmp;
  return tmp;
}

template<typename T>
T g(const T& x)
{
  return x * x;
}

int main()
{
  taylor<double, 1, 1> eps(2, 0);
  std::cout << f(eps) << "\n";
  std::cout << g(eps) << "\n";
}
```
the result does not correspond to what I expect. Essentially, both `f` and `g` compute the function `x^2`, albeit in different ways. Please correct me if I misunderstood how to use `libtaylor`, but I think with my definition of `eps`, the calls to `f` and `g` should both yield, as the first value, `x^2` evaluated at `x=2`, and as the second value, the first derivative of `x^2`, i.e. `2x`, evaluated at `x=2`. So I expect the output of both `f` and `g` to be `{4, 4}`, but `f` gives `{4, 6}`.

Unfortunately, in the application I want to use `libtaylor` in I can't just rewrite all target functions so as to avoid `operator*=`.

This behavior also occurs in the follwoing example:
```C++
#include <iostream>
#include "taylor.hpp"

int main()
{
  taylor<double, 1, 1> eps(2, 0);
  eps *= eps;
  std::cout << eps << "\n";
}
```

Thanks for making your software available!

**Comment by uekstrom** [comment]
Hi David, I think I have not considered this use of *=, which is a bug. The
problem is that tmp (in the first example) gets overwritten half way
through the calculation and the result is wrong. I actually have code to
compute x^2 "in-place" but apparently this is not used here. I will try to
get time tomorrow to fix this (there has to be a check if source is the
same as destination).

Regards,
Ulf

2017-02-07 17:13 GMT+01:00 David Toneian <notifications@github.com>:

**Comment by uekstrom** [comment]
I have committed a fix. Thanks for finding this bug!
