### ISSUE TITLE
What is the canonical version of libtaylor?

### ISSUE THREAD

**Issue by robertodr** [uekstrom/libtaylor#2]
If I look at the version of libtaylor in [XCFun](https://github.com/dftlibs/xcfun/tree/master/src/taylor) I see there are more files/different distribution of code among files than in the master branch of this repository. What is the canonical version of the libtaylor among the two?

**Comment by uekstrom** [comment]
It should be this repo but this should be double checked vs the version in
xcfun.

Ulf

2017-05-11 14:00 GMT+02:00 Roberto Di Remigio <notifications@github.com>:

**Comment by robertodr** [comment]
I will diff the two versions and let you know. Thanks!

**Comment by robertodr** [comment]
See PR #4
